#!/bin/bash

binLocation="$( cd "$( dirname "$( readlink -m "${BASH_SOURCE[0]}" )")" && pwd )"
echo "Found bin at ${binLocation}"
if [[ ! -e "/usr/local/bin/igbm" ]]; then
  echo "Creating link."
  cd /usr/local/bin
  ln -s "${binLocation}/igbm" igbm
else
  echo "Link exists. Skipping"
fi

echo "Cleaning up...."
rm "${binLocation}/linkToBin"