#!/bin/bash
##############################################################################
#
# Database Backup Script Manpage Generator
#
# Copyright (c) 2017 Shane Rogers
#
# License: BSD-3-Clause, see LICENSE file
#
##############################################################################

if ! which help2man 1>/dev/null 2>&1; then
  echo "ERROR: Can not find help2man." 1>&2
  exit 127
fi

rootDirectory="$( cd "$( dirname "$( dirname "$( readlink -m "${BASH_SOURCE[0]}" )")")" && pwd )"
devDirectory="${rootDirectory}/dev"

scriptName="igbm"

backupScript="${rootDirectory}/${scriptName}";

outputDirectory="${rootDirectory}/man/man1/"
outputFile="${scriptName}.1"
outputFileLocation="${outputDirectory}/${outputFile}"

# Generate the man page for the main utility
help2man -s1 -N --manual "IG Backup Manager" --name "IG Backup manager" \
	--output "${outputFileLocation}" \
    --opt-include "${devDirectory}/man/${scriptName}" \
    "${backupScript}"

gzip "${outputFileLocation}"
